// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe52uthfwGnjGS7fa2goQjn9YlR0fk8fM',
    appId: '1:1018621739274:web:c0859648c161c8c401baf3',
    messagingSenderId: '1018621739274',
    projectId: 'kesayangancoffe',
    authDomain: 'kesayangancoffe.firebaseapp.com',
    storageBucket: 'kesayangancoffe.firebasestorage.app',
    measurementId: 'G-W7VP27Y7KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1QOd59JYZ1DTM1jqdu3QN5zqaeHEjO8',
    appId: '1:1018621739274:android:675a935a6db0a02701baf3',
    messagingSenderId: '1018621739274',
    projectId: 'kesayangancoffe',
    storageBucket: 'kesayangancoffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmoO0SPvU-Y9Er1Iwl9njGe2vi2NOatzI',
    appId: '1:1018621739274:ios:e3f82f1e8a3e439101baf3',
    messagingSenderId: '1018621739274',
    projectId: 'kesayangancoffe',
    storageBucket: 'kesayangancoffe.firebasestorage.app',
    iosBundleId: 'com.example.uhuyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmoO0SPvU-Y9Er1Iwl9njGe2vi2NOatzI',
    appId: '1:1018621739274:ios:e3f82f1e8a3e439101baf3',
    messagingSenderId: '1018621739274',
    projectId: 'kesayangancoffe',
    storageBucket: 'kesayangancoffe.firebasestorage.app',
    iosBundleId: 'com.example.uhuyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe52uthfwGnjGS7fa2goQjn9YlR0fk8fM',
    appId: '1:1018621739274:web:fe6d5e8e0ed483b401baf3',
    messagingSenderId: '1018621739274',
    projectId: 'kesayangancoffe',
    authDomain: 'kesayangancoffe.firebaseapp.com',
    storageBucket: 'kesayangancoffe.firebasestorage.app',
    measurementId: 'G-07FXGD7MR0',
  );
}
